apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  labels:
    app: flask-app
spec:
  selector:
    matchLabels:
      app: flask-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  replicas: 2
  template:
    metadata:
      labels:
        app: flask-app
    spec: 
      containers:
        - name: flask-app
          image: flask-app:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
