#!/bin/bash 

#install kind https://kind.sigs.k8s.io/docs/user/quick-start/#installation
#install kubectl https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/

curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.11.1/kind-linux-amd64
chmod +x ./kind
sudo mv ./kind /usr/local/bin

curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
chmod +x ./kubectl
sudo mv ./kubectl /usr/local/bin/kubectl

kind create cluster --config kubernetes-cluster.yaml